[package]
name = "mtx"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.29"
nom = "8.0.0"
quote = "1.0.41"
rustpython-parser = "0.4.0"
thiserror = "2.0.17"
tokio-util = {"version" = "*", "features" = ["io"]}
